### ISSUE TITLE
RPCA Query

### ISSUE THREAD

**Issue by Dexter123193** [IoSR-Surrey/untwist#4]
Hi,
Is the given RPCA code able to do single source separation ?
If so, then how is it performing this task?
All it gives as a result is the estimated vocal result which is almost identical to the input?
How can this code be used for separation of singing voices.

**Comment by deeuu** [comment]
Hi,
>Is the given RPCA code able to do single source separation ?

Yes see [this](https://sites.google.com/site/singingvoiceseparationrpca/).
>then how is it performing this task?

I believe the code is based on [this](http://perception.csl.illinois.edu/matrix-rank/sample_code.html#RPCA).
>All it gives as a result is the estimated vocal result which is almost identical to the input?

I'm going to close this issue as it will be dealt with [here](https://github.com/IoSR-Surrey/untwist/issues/3)
