### ISSUE TITLE
MLP Issue 

### ISSUE THREAD

**Issue by Dexter123193** [IoSR-Surrey/untwist#5]
Hi. 
I am trying to run the mlp example of the untwist toolbox. 
I am getting this error "ValueError: operands could not be broadcast together with shapes (441000,) (110250,) " 
I have used the trim cmmd of sox to make both the audio files of same sizes. 
![screenshot from 2017-08-09 14-29-05](https://user-images.githubusercontent.com/30825115/29114924-2caa7ab6-7d0f-11e7-82d0-6c3ac41709c1.png)

**Comment by deeuu** [comment]
Hi,

I've just checked with two audio files of the same size and don't run into this issue.
Perhaps one/both of your files are < 10s to begin with?

You can check by adding:
`print(target.shape, background.shape)`
prior to mixing them (`mix = target + background`).

Alternatively, do something like:
```python
dur = 2
dur_in_samples = int(dur * 44100)
target = Wave.read("/home/dominic/target.wav")[:dur_in_samples,0]
background = Wave.read("/home/dominic/background.wav")[:dur_in_samples,0]
print(target.shape, background.shape)
```
where `dur` is known to be less than the duration (in seconds) of both files.

Cheers

**Comment by deeuu** [comment]
Please see the revised [example](https://github.com/IoSR-Surrey/untwist/blob/master/examples/mlp_example.py)
