### ISSUE TITLE
Error/type-o in mlp_examples.py

### ISSUE THREAD

**Issue by LinkOne1A** [IoSR-Surrey/untwist#6]
In the following block of code found in file mlp_examples.py, lines 38-40
     Xtrain = X[:,train_frames:].magnitude().T
     Xtest = ds.standardize_points(**Xtest**)
     pred = sgd.predict(Xtest)
    
I believe there is a typo-o, where in the middle code line above, Xtest is used before it is defined.
It seems to me that it is actually a type-o, and that the 2nd line of code should pass in Xtrain instead.

So the corrected lines of code would look like this
     Xtrain = X[:,train_frames:].magnitude().T
     Xtest = ds.standardize_points(**Xtrain**)
     pred = sgd.predict(Xtest)

**Comment by deeuu** [comment]
Hi,
Yes, you are correct, thanks.
This has already been corrected in the `dev` branch which I will be merging this week.
Sorry for the inconvenience.
